# Generated by Django 4.2.20 on 2025-04-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hoodie', 'Hoodie'), ('tshirt', 'T-Shirt'), ('trouser', 'Trouser'), ('sweatshirt', 'Sweatshirt')], max_length=255),
        ),
    ]
