# Generated by Django 4.2.20 on 2025-04-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MS', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('eSewa', 'eSewa'), ('COD', 'Cash on Delivery')], default='COD', max_length=20),
        ),
    ]
